language: python

python:
  - "2.7"

env:
  - CONDA_DEPS="pip flake8 nose coverage numpy scipy matplotlib" PIP_DEPS="coveralls"

before_install:
- export MINICONDA=$HOME/miniconda
- export PATH="$MINICONDA/bin:$PATH"
- hash -r
# Install conda only if necessary
- command -v conda >/dev/null || { wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
- bash miniconda.sh -b -f -p $MINICONDA; }
- conda config --set always_yes yes
- conda update conda
- conda info -a
#- conda install python=$TRAVIS_PYTHON_VERSION $CONDA_DEPS
#- travis_retry pip install $PIP_DEPS

install:
# creating the conda environment
- conda create -q -n CNMF python=$TRAVIS_PYTHON_VERSION
- source activate CNMF
- python setup.py install

#install:
#- python setup.py install --record installed_files.txt

#script:
#- nosetests -v --with-coverage --cover-package=shablona
#- flake8 --ignore N802,N806 `find . -name \*.py | grep -v setup.py | grep -v /doc/`

#after_success:
#- coveralls

before_cache:
# clean unused packages & installed files from conda cache
# this makes the cache rebuilt less frequently
- conda clean --tarballs --packages --index-cache
- rm -rf $HOME/miniconda/pkgs/cache
- xargs rm <installed_files.txt

cache:
  directories:
    - $HOME/miniconda

# whitelist
branches:
  only:
    - testing
