language: python

services:
  - docker

before_install:
  - docker build -t valentina/constrained_nmf .
  - docker run -d -p 127.0.0.1:80:4567 valentina/constrained_nmf /bin/sh -c "ls"

script:
  - docker ps


# whitelist
branches:
  only:
    - testing
    - CNMF2
    - anaconda
    - docker
