language: python

python:
  - "2.7"

compiler:
  - gcc
  - gfortran

addons:
  apt:
    packages:
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - gfortran

env:
  - CONDA_DEPS="pip flake8 nose coverage numpy scikit-learn" PIP_DEPS="coveralls"

before_install:
- export MINICONDA=$HOME/miniconda
- export PATH="$MINICONDA/bin:$PATH"
- hash -r
# Install conda only if necessary
- wget -q http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
- bash miniconda.sh -b -f -p $MINICONDA
- conda config --set always_yes yes
- conda update --yes conda
- conda info -a
# - conda install python=$TRAVIS_PYTHON_VERSION $CONDA_DEPS
#- travis_retry pip install $PIP_DEPS

install:
# creating the conda environment
#- conda create -q -n CNMF  python=$TRAVIS_PYTHON_VERSION scikit-learn
#- python --version
- conda install scikit-learn
# - source activate CNMF
- conda install psutil
- python setup.py install
- conda install nose
- conda install ipyparallel
- conda install scikit-image



#install:
#- python setup.py install --record installed_files.txt

#script:
#- nosetests -v --with-coverage --cover-package=shablona
#- flake8 --ignore N802,N806 `find . -name \*.py | grep -v setup.py | grep -v /doc/`

#after_success:
#- coveralls

# before_cache:
# clean unused packages & installed files from conda cache
# this makes the cache rebuilt less frequently

#- conda clean --tarballs --packages --index-cache
#- rm -rf $HOME/miniconda/pkgs/cache
#- xargs rm <installed_files.txt

#cache:
#  directories:
#    - $HOME/miniconda

script:
  # - python -c "import numpy; print numpy.version.version"
  - which nosetests
  - nosetests

# whitelist
branches:
  only:
    - testing
    - CNMF2
